### PR TITLE
Add Display impl for AugmentedScriptSet

### PR DESCRIPTION
**Pull request by Manishearth**
cc @crlf0710

### CODE REVIEW

**Comment by crlf0710** [comment]
Fixed a small typo and added a unit test. Do we want to use comma to separate the items here, or use the plus mentioned in #72770 ?

**Comment by crlf0710** [comment]
By the way, I'm also a little tempted to use "Chinese" instead of "Han with Bopomofo" :)

**Comment by Manishearth** [comment]
Plus is fine too

**Comment by Manishearth** [comment]
I'm using the official spec name for it

**Pull request merged**
